### ISSUE TITLE
shm_open doesn't work

### ISSUE THREAD

**Issue by beelzetron** [debarshiray/fedora-toolbox#9] opened 2018-10-31 07:46 UTC
Hi,
when I run a playbook inside the fedora-toolbox created container it returns the following error:
`ERROR! Unable to use multiprocessing, this is normally caused by lack of access to /dev/shm: [Errno 30] Read-only file system`

**Comment by debarshiray** [comment] 2018-11-06 18:50
I can reproduce this with:
```
/* gcc shm.c -lrt */

#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <sys/mman.h>

int
main (void)
{
  int fd;

  fd = shm_open ("/foo", O_CREAT | O_RDWR, 0664);
  if (fd == -1)
    {
      fprintf (stderr, "shm_open failed: %s\n", strerror (errno));
      return 1;
    }

  close (fd);
  return 0;
}
```

However, this works:
```
🔹[rishi@toolbox ~]$ echo hello world >/dev/shm/bar
🔹[rishi@toolbox ~]$ ls -l /dev/shm
total 4
-rw-rw-r--. 1 rishi rishi 12 Nov  6 18:48 bar
🔹[rishi@toolbox ~]$ cat /dev/shm/bar
hello world
```

**Comment by debarshiray** [comment] 2018-11-06 18:52
That tells me that `open` works, but `shm_open` doesn't.

**Comment by debarshiray** [comment] 2018-11-07 15:55
Does PR #12 fix the problem for you?

**Comment by debarshiray** [comment] 2018-11-08 13:41
I am closing this issue because the above `shm_open` reproducer now works for me. Feel free to reopen or leave a comment if you have reason to think otherwise.

Either way, thanks for trying `fedora-toolbox` and getting in touch!

**Closed by debarshiray** 2018-11-08 13:41 UTC
