### ISSUE TITLE
Bubblewrap doesn't work inside the toolbox when UID != 0

### ISSUE THREAD

**Issue by Logibox** [debarshiray/fedora-toolbox#17] opened 2018-11-12 15:13 UTC
Here's what happens when you run `bwrap` when inside the container:
```
🔹[myates@toolbox buildstream-storeonce]$ bwrap --version
bubblewrap 0.3.1
🔹[myates@toolbox buildstream-storeonce]$ bwrap --help
bwrap: Unexpected capabilities but not setuid, old file caps config?
🔹[myates@toolbox buildstream-storeonce]$ sudo bwrap --help
usage: bwrap [OPTIONS...] [--] COMMAND [ARGS...]

    --help                       Print this help
    --version                    Print version
...
```
Same results for all other options too.

Is this an issue with rootless containers in podman?

**Comment by Logibox** [comment] 2019-01-11 18:11
It requirement to run [buildstream](https://gitlab.com/BuildStream/buildstream) actually (alongside fuse for overlayfs, but that's covered by #15).

I suspect that it may more helpful if I check if `bwrap` works in a rootless containers at all in `podman` and track the issue in containers/libpod, rather than here.

**Comment by Logibox** [comment] 2019-01-11 18:17
[Building flatpaks](https://github.com/flatpak/flatpak-builder) also requires `bwrap`, so that might require running as root in the toolbox.

Although I've not tried this.

**Comment by debarshiray** [comment] 2019-02-05 15:44
Duplicate of #16

**Closed** 2019-02-05 15:46 UTC
