### ISSUE TITLE
/dev/fuse not available in the toolbox

### ISSUE THREAD

**Issue by Logibox** [debarshiray/fedora-toolbox#15] opened 2018-11-09 14:59 UTC
Is it possible to add a `--volume /dev/fuse:/dev/fuse` when creating the toolbox to facilitate this?

**Comment by debarshiray** [comment] 2019-01-11 15:04
@Logibox does #36 help?

It would be nice to know your use-case so that I could test that it actually works as intended. :)

**Comment by Logibox** [comment] 2019-01-11 17:57
Thanks, that patch looks like it would do the job, but I'm not at my workstation now to test it :(.

The reason I raised the issue was I find myself using [sshfs](https://github.com/libfuse/sshfs) in my workflows, and couldn't inside the toolbox.

**Comment by debarshiray** [comment] 2019-01-14 11:03
Closing, after @Logibox confirmed the fix in #36.

**Closed by debarshiray** 2019-01-14 11:03 UTC
