### ISSUE TITLE
~/.config/containers/storage.conf oscillates between camel and lower case formats

### ISSUE THREAD

**Issue by alex285** [debarshiray/fedora-toolbox#42] opened 2019-01-24 15:25 UTC
I dont have any existing containers

Podman: version 1.0.0
Buildah: version 1.5
SB: version: 29.20190124.0

**./fedora-toolbox create**

```
unable to pull fedora-toolbox-me:29: 5 errors occurred:

* Error determining manifest MIME type for docker://fedora-toolbox-me:29: Error reading manifest 29 in docker.io/library/fedora-toolbox-me: errors:
denied: requested access to the resource is denied
unauthorized: authentication required

* Error determining manifest MIME type for docker://registry.fedoraproject.org/fedora-toolbox-me:29: Error reading manifest 29 in registry.fedoraproject.org/fedora-toolbox-me: manifest unknown: manifest unknown
* Error determining manifest MIME type for docker://quay.io/fedora-toolbox-me:29: Error reading manifest 29 in quay.io/fedora-toolbox-me: error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>\n"
* Error determining manifest MIME type for docker://registry.access.redhat.com/fedora-toolbox-me:29: Error reading manifest 29 in registry.access.redhat.com/fedora-toolbox-me: unknown: Not Found
* Error determining manifest MIME type for docker://registry.centos.org/fedora-toolbox-me:29: Error reading manifest 29 in registry.centos.org/fedora-toolbox-me: manifest unknown: manifest unknown
./fedora-toolbox: failed to create container fedora-toolbox-me:29
```

**podman info**
```
{
    "Type": "buildah 0.0.1",
    "FromImage": "localhost/fedora-toolbox-me:29",
    "FromImageID": "f30c58dee8c7922ff93dab4ca085a63223b866c65e3cb34d5d0b03ed40e9be5a",
    "Config": "{\"created\":\"2019-01-24T13:49:36.765963759Z\",\"architecture\":\"amd64\",\"os\":\"linux\",\"config\":{\"User\":\"me\",\"Env\":[\"DISTTAG=f29container\",\"FGC=f29\",\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\",\"NAME=fedora-toolbox\",\"VERSION=29\"],\"Cmd\":[\"/bin/sh\",\"-c\",\"/bin/sh\"],\"Volumes\":{\"/dev/dri\":{},\"/dev/fuse\":{},\"/home/me\":{},\"/run/dbus/system_bus_socket\":{},\"/run/user/1000\":{}},\"WorkingDir\":\"/home/me\",\"Labels\":{\"architecture\":\"x86_64\",\"authoritative-source-url\":\"registry.fedoraproject.org\",\"build-date\":\"2018-09-27T10:36:46.898719\",\"com.redhat.build-host\":\"osbs-node01.phx2.fedoraproject.org\",\"com.redhat.component\":\"fedora-toolbox\",\"distribution-scope\":\"public\",\"license\":\"MIT\",\"maintainer\":\"Debarshi Ray \\u003crishi@fedoraproject.org\\u003e\",\"name\":\"f29/fedora-toolbox\",\"release\":\"1\",\"summary\":\"Base image for creating Fedora toolbox containers\",\"usage\":\"This image is meant to be used with the fedora-toolbox command\",\"vcs-ref\":\"2bb7cf2dffd8da870555967015d7d6074cd9d1b4\",\"vcs-type\":\"git\",\"vendor\":\"Fedora Project\",\"version\":\"29\"}},\"rootfs\":{\"type\":\"layers\",\"diff_ids\":[\"sha256:8080f9aa6262000ad12d3d7e55331d275d412faa730b75c41bbf444b4ce056e9\",\"sha256:d399ea65472cbad41d640ec2a09724c2f11ac7fa52636b6cec6905e8fa490865\",\"sha256:1249db3c77ad001b27404926eb643fbe96db22d3c8f1d091e597e1297608a348\"]},\"history\":[{\"created\":\"2018-09-17T12:27:24Z\",\"comment\":\"Created by Image Factory\"},{\"created\":\"2018-09-27T10:47:13.800071Z\"},{\"created\":\"2019-01-24T13:49:36.765963759Z\"}]}",
    "Manifest": "{\"schemaVersion\":2,\"config\":{\"mediaType\":\"application/vnd.oci.image.config.v1+json\",\"digest\":\"sha256:f30c58dee8c7922ff93dab4ca085a63223b866c65e3cb34d5d0b03ed40e9be5a\",\"size\":1477},\"layers\":[{\"mediaType\":\"application/vnd.oci.image.layer.v1.tar\",\"digest\":\"sha256:8080f9aa6262000ad12d3d7e55331d275d412faa730b75c41bbf444b4ce056e9\",\"size\":268318720},{\"mediaType\":\"application/vnd.oci.image.layer.v1.tar\",\"digest\":\"sha256:d399ea65472cbad41d640ec2a09724c2f11ac7fa52636b6cec6905e8fa490865\",\"size\":309514240},{\"mediaType\":\"application/vnd.oci.image.layer.v1.tar+gzip\",\"digest\":\"sha256:a6be2e6c036b18f70eeff8feee80b2e3fefa5f1835b8e1010cc83d838174a414\",\"size\":2026}]}",
    "Container": "",
    "ContainerID": "",
    "MountPoint": "",
    "ProcessLabel": "",
    "MountLabel": "",
    "ImageAnnotations": null,
    "ImageCreatedBy": "",
    "OCIv1": {
        "created": "2019-01-24T13:49:36.765963759Z",
        "architecture": "amd64",
        "os": "linux",
        "config": {
            "User": "me",
            "Env": [
                "DISTTAG=f29container",
                "FGC=f29",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NAME=fedora-toolbox",
                "VERSION=29"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "/bin/sh"
            ],
            "Volumes": {
                "/dev/dri": {},
                "/dev/fuse": {},
                "/home/me": {},
                "/run/dbus/system_bus_socket": {},
                "/run/user/1000": {}
            },
            "WorkingDir": "/home/me",
            "Labels": {
                "architecture": "x86_64",
                "authoritative-source-url": "registry.fedoraproject.org",
                "build-date": "2018-09-27T10:36:46.898719",
                "com.redhat.build-host": "osbs-node01.phx2.fedoraproject.org",
                "com.redhat.component": "fedora-toolbox",
                "distribution-scope": "public",
                "license": "MIT",
                "maintainer": "Debarshi Ray \u003crishi@fedoraproject.org\u003e",
                "name": "f29/fedora-toolbox",
                "release": "1",
                "summary": "Base image for creating Fedora toolbox containers",
                "usage": "This image is meant to be used with the fedora-toolbox command",
                "vcs-ref": "2bb7cf2dffd8da870555967015d7d6074cd9d1b4",
                "vcs-type": "git",
                "vendor": "Fedora Project",
                "version": "29"
            }
        },
        "rootfs": {
            "type": "layers",
            "diff_ids": [
                "sha256:8080f9aa6262000ad12d3d7e55331d275d412faa730b75c41bbf444b4ce056e9",
                "sha256:d399ea65472cbad41d640ec2a09724c2f11ac7fa52636b6cec6905e8fa490865",
                "sha256:1249db3c77ad001b27404926eb643fbe96db22d3c8f1d091e597e1297608a348"
            ]
        },
        "history": [
            {
                "created": "2018-09-17T12:27:24Z",
                "comment": "Created by Image Factory"
            },
            {
                "created": "2018-09-27T10:47:13.800071Z"
            },
            {
                "created": "2019-01-24T13:49:36.765963759Z"
            }
        ]
    },
    "Docker": {
        "created": "2019-01-24T13:49:36.765963759Z",
        "container_config": {
            "Hostname": "",
            "Domainname": "",
            "User": "me",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "DISTTAG=f29container",
                "FGC=f29",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NAME=fedora-toolbox",
                "VERSION=29"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "/bin/sh"
            ],
            "Image": "",
            "Volumes": {
                "/dev/dri": {},
                "/dev/fuse": {},
                "/home/me": {},
                "/run/dbus/system_bus_socket": {},
                "/run/user/1000": {}
            },
            "WorkingDir": "/home/me",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "architecture": "x86_64",
                "authoritative-source-url": "registry.fedoraproject.org",
                "build-date": "2018-09-27T10:36:46.898719",
                "com.redhat.build-host": "osbs-node01.phx2.fedoraproject.org",
                "com.redhat.component": "fedora-toolbox",
                "distribution-scope": "public",
                "license": "MIT",
                "maintainer": "Debarshi Ray \u003crishi@fedoraproject.org\u003e",
                "name": "f29/fedora-toolbox",
                "release": "1",
                "summary": "Base image for creating Fedora toolbox containers",
                "usage": "This image is meant to be used with the fedora-toolbox command",
                "vcs-ref": "2bb7cf2dffd8da870555967015d7d6074cd9d1b4",
                "vcs-type": "git",
                "vendor": "Fedora Project",
                "version": "29"
            }
        },
        "config": {
            "Hostname": "",
            "Domainname": "",
            "User": "me",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "DISTTAG=f29container",
                "FGC=f29",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NAME=fedora-toolbox",
                "VERSION=29"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "/bin/sh"
            ],
            "Image": "",
            "Volumes": {
                "/dev/dri": {},
                "/dev/fuse": {},
                "/home/me": {},
                "/run/dbus/system_bus_socket": {},
                "/run/user/1000": {}
            },
            "WorkingDir": "/home/me",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "architecture": "x86_64",
                "authoritative-source-url": "registry.fedoraproject.org",
                "build-date": "2018-09-27T10:36:46.898719",
                "com.redhat.build-host": "osbs-node01.phx2.fedoraproject.org",
                "com.redhat.component": "fedora-toolbox",
                "distribution-scope": "public",
                "license": "MIT",
                "maintainer": "Debarshi Ray \u003crishi@fedoraproject.org\u003e",
                "name": "f29/fedora-toolbox",
                "release": "1",
                "summary": "Base image for creating Fedora toolbox containers",
                "usage": "This image is meant to be used with the fedora-toolbox command",
                "vcs-ref": "2bb7cf2dffd8da870555967015d7d6074cd9d1b4",
                "vcs-type": "git",
                "vendor": "Fedora Project",
                "version": "29"
            }
        },
        "architecture": "amd64",
        "os": "linux",
        "rootfs": {
            "type": "layers",
            "diff_ids": [
                "sha256:8080f9aa6262000ad12d3d7e55331d275d412faa730b75c41bbf444b4ce056e9",
                "sha256:d399ea65472cbad41d640ec2a09724c2f11ac7fa52636b6cec6905e8fa490865",
                "sha256:1249db3c77ad001b27404926eb643fbe96db22d3c8f1d091e597e1297608a348"
            ]
        },
        "history": [
            {
                "created": "2018-09-17T12:27:24Z",
                "comment": "Created by Image Factory"
            },
            {
                "created": "2018-09-27T10:47:13.800071Z"
            },
            {
                "created": "2019-01-24T13:49:36.765963759Z"
            }
        ]
    },
    "DefaultMountsFilePath": "",
    "Isolation": "IsolationDefault",
    "NamespaceOptions": [
        {
            "Name": "cgroup",
            "Host": true,
            "Path": ""
        },
        {
            "Name": "ipc",
            "Host": false,
            "Path": ""
        },
        {
            "Name": "mount",
            "Host": false,
            "Path": ""
        },
        {
            "Name": "network",
            "Host": false,
            "Path": ""
        },
        {
            "Name": "pid",
            "Host": false,
            "Path": ""
        },
        {
            "Name": "user",
            "Host": true,
            "Path": ""
        },
        {
            "Name": "uts",
            "Host": false,
            "Path": ""
        }
    ],
    "ConfigureNetwork": "NetworkDefault",
    "CNIPluginPath": "",
    "CNIConfigDir": "",
    "IDMappingOptions": {
        "HostUIDMapping": true,
        "HostGIDMapping": true,
        "UIDMap": [],
        "GIDMap": []
    },
    "DefaultCapabilities": [
        "CAP_AUDIT_WRITE",
        "CAP_CHOWN",
        "CAP_DAC_OVERRIDE",
        "CAP_FOWNER",
        "CAP_FSETID",
        "CAP_KILL",
        "CAP_MKNOD",
        "CAP_NET_BIND_SERVICE",
        "CAP_SETFCAP",
        "CAP_SETGID",
        "CAP_SETPCAP",
        "CAP_SETUID",
        "CAP_SYS_CHROOT"
    ],
    "AddCapabilities": [],
    "DropCapabilities": []
}
```

**Comment by alex285** [comment] 2019-01-24 15:46
possibly related to: https://github.com/containers/libpod/issues/1516

```
ERRO[0000] 'overlay' is not supported over extfs at "/var/home/jonessean/.local/share/containers/storage/overlay" 
error creating libpod runtime: kernel does not support overlay fs: 'overlay' is not supported over extfs at "/var/home/jonessean/.local/share/containers/storage/overlay": backing file system is unsupported for this graph driver
```

**Comment by debarshiray** [comment] 2019-01-24 16:49
> This is very likely https://github.com/containers/libpod/issues/2158

Yes, and I think that's a duplicate of https://github.com/containers/libpod/issues/2158

If your `~/.config/containers/storage.conf` is using the camel case format, then try switch to the lower case format, remove `~/.local/share/containers`, and retry `fedora-toolbox`. See the above `libpod` issue about the formats.

**Comment by alex285** [comment] 2019-01-24 18:45
@debarshiray that fixed it for me! thanks

a smaller issue is that if `~/.local/containers` folder is missing, FT stacks on ` checking if image fedora-toolbox-me:29 already exists`

**Comment by jurf** [comment] 2019-01-24 21:10
@debarshiray yep, fixed it for me too, thanks! Any idea what the problem might’ve been?

**Comment by debarshiray** [comment] 2019-01-26 11:40
> a smaller issue is that if `~/.local/containers` folder is missing, FT stacks on
> ` checking if image fedora-toolbox-me:29 already exists`

You mean `~/.local/share/containers`? Which versions of `podman` and `buildah` do you have? In any case, that's going to be a bug in those tools, not `fedora-toolbox` itself.

Closing as a duplicate of https://github.com/containers/libpod/issues/2158

**Closed by debarshiray** 2019-01-26 11:40 UTC

**Comment by alex285** [comment] 2019-01-27 05:11
versions were listed on my initial report, but yeah i should open it elsewhere!
