### ISSUE TITLE
setup user: cannot set any additional groups in a rootless container

### ISSUE THREAD

**Issue by j1mc** [debarshiray/fedora-toolbox#7] opened 2018-10-28 01:00 UTC
Encountered this error after doing `./fedora-toolbox create` and `fedora-toolbox enter`.  I only cloned the repo and then tried those commands. If there are other setup instructions needed, feel free to inform us.  : )  Thanks!

`[jwc@localhost fedora-toolbox]$ ./fedora-toolbox -v enter
unable to start container "fedora-toolbox-jwc:29": container create failed: container_linux.go:336: starting container process caused "setup user: cannot set any additional groups in a rootless container"
: internal libpod error
./fedora-toolbox: failed to start container fedora-toolbox-jwc:29
`

**Comment by commagray** [comment] 2018-10-28 15:59
Same here, Fedora Silverblue 29.

**Comment by krashekspres** [comment] 2018-10-29 15:10
It would help if you paste podman, runc versions.
For F29 I know for sure that you have to override runc version (https://github.com/debarshiray/fedora-toolbox/issues/4#issuecomment-432184146)

**Comment by debarshiray** [comment] 2018-10-29 16:44
Yes, this is certainly a duplicate of #4.

**Closed by debarshiray** 2018-10-29 16:44 UTC
