### ISSUE TITLE
failed to create container

### ISSUE THREAD

**Issue by seandjones92** [debarshiray/fedora-toolbox#25] opened 2018-12-13 19:46 UTC
I'm having issues getting started with fedora-toolbox. I am able to recreate this reliably even in a freshly deployed VM.

```
➜  fedora-toolbox git:(master) ./fedora-toolbox -v create           
error reading image "fedora-toolbox-sean:29": error reading image: error locating image "fedora-toolbox-sean:29" for importing settings: error locating image with name "fedora-toolbox-sean:29": image not known
ERRO[0000] exit status 1                                
Error determining manifest MIME type for docker://localhost/fedora-toolbox:29: pinging docker registry returned: Get https://localhost/v2/: dial tcp [::1]:443: connect: connection refused
ERRO[0000] exit status 1                                
Getting image source signatures
Copying blob sha256:af19ce19de5ee70d1ca852c65f9927fab6ba09de2864af2acdf18d60774bffbd
 85.70 MiB / 85.70 MiB [===================================================] 10s
Copying blob sha256:6df1bfffa76ae08ebcb61de2ae28fbf5f8a84079b6cb316d095cdf4cb5e2bdbb
 182.56 MiB / 182.56 MiB [=================================================] 20s
Copying config sha256:032b427fbbf72ac22336638af319ef989a2b99e038ca087743c132ab71445ed8
 2.69 KiB / 2.69 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
bpasswd: Note: deleting a password also unlocks the password.
passwd: Note: deleting a password also unlocks the password.
Getting image source signatures
Skipping fetch of repeat blob sha256:8080f9aa6262000ad12d3d7e55331d275d412faa730b75c41bbf444b4ce056e9
Skipping fetch of repeat blob sha256:d399ea65472cbad41d640ec2a09724c2f11ac7fa52636b6cec6905e8fa490865
Copying blob sha256:e3518f4673581285a8029c0503002cbc08ff0c737a73449888b3d42af3522b36
 1.94 KiB / 1.94 KiB [======================================================] 0s
Copying config sha256:2c61bc9552383aad9f8e1579f8a31d7ba15a7bfa1b9fbc7f275ef98ca2422c8e
 1.43 KiB / 1.43 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
error looking up container "fedora-toolbox-sean:29": no container with name or ID fedora-toolbox-sean:29 found: no such container
Trying to pull docker.io/fedora-toolbox-sean:29...Failed
Trying to pull registry.fedoraproject.org/fedora-toolbox-sean:29...Failed
Trying to pull quay.io/fedora-toolbox-sean:29...Failed
Trying to pull registry.access.redhat.com/fedora-toolbox-sean:29...Failed
Trying to pull registry.centos.org/fedora-toolbox-sean:29...Failed
unable to pull fedora-toolbox-sean:29: 5 errors occurred:

* Error determining manifest MIME type for docker://fedora-toolbox-sean:29: Error reading manifest 29 in docker.io/library/fedora-toolbox-sean: errors:
denied: requested access to the resource is denied
unauthorized: authentication required

* Error determining manifest MIME type for docker://registry.fedoraproject.org/fedora-toolbox-sean:29: Error reading manifest 29 in registry.fedoraproject.org/fedora-toolbox-sean: manifest unknown: manifest unknown
* Error determining manifest MIME type for docker://quay.io/fedora-toolbox-sean:29: Error reading manifest 29 in quay.io/fedora-toolbox-sean: error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>\n"
* Error determining manifest MIME type for docker://registry.access.redhat.com/fedora-toolbox-sean:29: Error reading manifest 29 in registry.access.redhat.com/fedora-toolbox-sean: unknown: Not Found
* Error determining manifest MIME type for docker://registry.centos.org/fedora-toolbox-sean:29: Error reading manifest 29 in registry.centos.org/fedora-toolbox-sean: manifest unknown: manifest unknown
./fedora-toolbox: failed to create container fedora-toolbox-sean:29
```

The README on this project doesn't make it obvious if there are any prerequisites that I should meet before running this, it sounds like I should just be able to run the script and get a working toolbox. 

Let me know if I'm missing anything or if you need any more info to get an idea of what is happening.

**Comment by juhp** [comment] 2018-12-27 08:19
Have you tried the fedora package?

**Comment by seandjones92** [comment] 2018-12-27 17:35
I didn't realize there was a package for this. I installed it with `rpm-ostree install fedora-toolbox`, rebooted and ran `fedora-toolbox -v create` and received the same message in my original post. 

In this bug (https://github.com/containers/libpod/issues/2015) it looks like this stems from a bug in libpod and might be fixed in a future release. 

Looks like the toolbox will remain broken for now

**Comment by seandjones92** [comment] 2018-12-28 23:33
So I've reinstalled Fedora Silverblue, installed `fedora-toolbox` with `rpm-ostree` and once again ran `fedora-toolbox -v create`. It printed all of the same errors in the original post but now when I run `podman ps -a` I can see a container named `fedora-toolbox-sean:29` even though the output of the command stated `failed to create container fedora-toolbox-sean:29`.

Not sure why this is or what caused it to work this time but the errors are all still present. Not sure if this is something you want to investigate any further.

**Comment by mikemorrell2** [comment] 2018-12-29 16:30
I too am getting this error. My error output is a this...
`[mike@mustang fedora-toolbox]$ ./fedora-toolbox -v create
error looking up container "fedora-toolbox-mike:29": no container with name or ID fedora-toolbox-mike:29 found: no such container
invalid container path, must be an absolute path ""
./fedora-toolbox: failed to create container fedora-toolbox-mike:29`

**Comment by mikemorrell2** [comment] 2018-12-31 13:01
Okay so I see that PR #22 was part of my problem. I fixed that and now I see the exact same output as Sean. But it seems that event though buildah has created and configured the image, podman cannot find the image for some reason.
`Writing manifest to image destination
Storing signatures
error looking up container "fedora-toolbox-mike:29": no container with name or ID fedora-toolbox-mike:29 found: no such container`
I am using an up to date silverblue ostree base. Here is the details...
`[mike@mustang fedora-toolbox]$ buildah -v
buildah version 1.5 (image-spec 1.0.0, runtime-spec 1.0.0)
[mike@mustang fedora-toolbox]$ podman -v
podman version 0.12.1.2
[mike@mustang fedora-toolbox]$ rpm-ostree status
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://fedora-workstation:fedora/29/x86_64/silverblue
                   Version: 29.20181230.0 (2018-12-30T01:02:02Z)
                BaseCommit: 37251e33ea38cf92dff8c863d1debd50bb6801003d73535f2aba006af2fbbf3f
`

**Comment by mikemorrell2** [comment] 2018-12-31 14:00
It found that the storge driver config for my local user was corrupted. After I removed all my buildah images and deleted the ~/.local/share/containers/storage directory and then re-run the fedora-toolbox create, it all worked correctly. Hope this can help someone else that is stuck on this.

**Comment by debarshiray** [comment] 2019-01-02 16:54
Yes, the original problem reported by @seandjones92 was caused by various incompatibilities between rootless `buildah` and rootless `podman` that had crept into the stable Silverblue images. That was very unfortunate, but it looks like the two of them are back together again.

Thanks for getting in touch. Closing.

**Closed by debarshiray** 2019-01-02 16:54 UTC
