### ISSUE TITLE
dbus_system_bus_path is only set if the toolbox image does not exist

### ISSUE THREAD

**Issue by kirbyfan64** [debarshiray/fedora-toolbox#26] opened 2018-12-18 04:15 UTC
If the image already exists, then that entire `if` will be skipped, and `podman create` will fail because the D-Bus socket volume argument will end up being `--volume :`. 

[Original issue on Fedora Discourse.](https://discussion.fedoraproject.org/t/an-image-for-a-fedora-toolbox-container/286/11?u=refi64)

**Comment by blaisep** [comment] 2018-12-18 05:49
So I deleted all the previous images and containers related to fedora-toolbox and did `fedora-toolbox create` It failed as usual, but I noticed that it did create an image, so I am attaching the output of `buildah inspect`:
[buildah_inspect_out.txt](https://github.com/debarshiray/fedora-toolbox/files/2689040/buildah_inspect_out.txt)

**Comment by juhp** [comment] 2018-12-27 08:47
I am hitting this too: before f29 I had a fedora-toolbox container working for 28, but I couldn't create a 29 image or container yet.

**Comment by jeslinmx** [comment] 2018-12-27 15:51
#22 solves this and has been waiting to be merged for some time.

**Comment by debarshiray** [comment] 2019-01-02 16:44
Duplicate of #19

**Closed by debarshiray** 2019-01-02 16:44 UTC

**Comment by debarshiray** [comment] 2019-01-02 16:46
@blaisep Yes, we really need to get a test suite in place! However, I am new enough to the world of Docker and Podman that I can't recommend a particular approach off the top of my head. Suggestions and patches welcome.
